[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    fastled/FastLED@^3.6.0
    bblanchon/ArduinoJson@^6.21.3
    links2004/WebSockets@^2.4.0
    ESP Async WebServer@^1.2.3
    AsyncTCP@^1.1.1
    
build_flags = 
    -DCORE_DEBUG_LEVEL=4
    -DFASTLED_ESP32_I2S=1
    
upload_speed = 921600