/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Rgb {
  r: number
  g: number
  b: number
}
export interface Frame {
  timeMs: number
  leds: Array<Rgb>
}
export interface AudioNote {
  startMs: number
  durationMs: number
  frequencyHz: number
  voice: number
  waveform: number
}
export interface Animation {
  durationMs: number
  frames: Array<Frame>
  audioNotes: Array<AudioNote>
}
export declare function encodeAnimationJs(animation: Animation): Array<number>
